# Generated by Django 3.2.16 on 2022-12-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('studentName', models.CharField(max_length=24)),
                ('studentRollNo', models.CharField(max_length=24)),
                ('studentBranch', models.CharField(default='cse', max_length=12)),
            ],
        ),
    ]
